root = "."
tmp_dir = "tmp"

[build]
  cmd = "templ generate && go build -o ./tmp/main ."
  entrypoint = ["./tmp/main"]
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = [".*_templ.go"]
  include_ext = ["go", "templ", "html"]
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = false
